export type Role = 'admin' | 'super_admin' | 'client' | 'developer';
export type ProjectStatus = 'draft' | 'published' | 'archived';
export interface User { id:string; email:string; name:string; role:Role; }
export interface SiteSettings { id:string; company_name:string; tagline:string; logo_light?:string|null; logo_dark?:string|null; favicon?:string|null; contact_email:string; contact_phone?:string|null; whatsapp?:string|null; address?:string|null; maps_embed?:string|null; working_hours?:string|null; social_links:Record<string,string>; footer_text?:string|null; default_seo_title:string; default_seo_description:string; share_image?:string|null; }
export interface Category { id:string; name:string; slug:string; description?:string|null; parent_id?:string|null; display_order:number; is_active:boolean; }
export interface Project { id:string; title:string; slug:string; summary:string; long_description?:string|null; client?:string|null; industry?:string|null; year?:number|null; services_provided:string[]; tech_stack:string[]; results:{label:string;value:string}[]; live_url?:string|null; repo_url?:string|null; cover_image?:string|null; status:ProjectStatus; featured:boolean; display_order:number; published_at?:string|null; seo_title?:string|null; seo_description?:string|null; category_id?:string|null; category?:Category; media?:ProjectMedia[]; }
export interface ProjectMedia { id:string; project_id:string; media_asset_id?:string|null; asset_url:string; media_type:'image'|'video'|'embed'|'document'; caption?:string|null; display_order:number; }
export interface MediaAsset { id:string; file_name:string; asset_url:string; media_type:'image'|'video'|'document'|'embed'; mime_type?:string|null; size_bytes?:number|null; alt_text?:string|null; created_at:string; }
export interface Service { id:string; name:string; slug:string; summary:string; description?:string|null; icon?:string|null; display_order:number; is_active:boolean; }
export interface PageSection { id:string; page_slug:string; section_key:string; content:Record<string,any>; display_order:number; is_visible:boolean; status:'draft'|'published'; }
export interface ContactSubmission { id:string; name:string; email:string; phone?:string|null; company?:string|null; project_type:string; budget_range?:string|null; message:string; status:'new'|'read'|'replied'|'archived'; internal_notes?:string|null; created_at:string; }
export const emptySettings:SiteSettings={id:'global',company_name:'Vision Built',tagline:'Digital products built with intent.',contact_email:'hello@visionbuilt.in',contact_phone:'',whatsapp:'',address:'',maps_embed:'',working_hours:'Mon–Fri, 9:00–18:00 IST',social_links:{},footer_text:'Built for the next useful thing.',default_seo_title:'Vision Built — Digital products built with intent',default_seo_description:'Vision Built designs and builds clear, durable digital products for ambitious teams.',share_image:''};
