import { supabase } from './supabase';
import { Category, ContactSubmission, MediaAsset, PageSection, Project, Service, SiteSettings, User, emptySettings } from '../types';

const BUCKET = 'portfolio-media';
const allowedTypes = new Set(['image/jpeg','image/png','image/webp','image/avif','image/gif','video/mp4','video/webm','video/quicktime','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/zip']);
const safeName = (name:string) => name.toLowerCase().normalize('NFKD').replace(/[^\w.\-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,''); const detectedMime=(file:File)=>file.type||({mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime',qt:'video/quicktime'} as Record<string,string>)[file.name.split('.').pop()?.toLowerCase()||'']||'';
async function maybeResize(file:File):Promise<File>{ if(!file.type.startsWith('image/') || file.type==='image/gif') return file; const bitmap=await createImageBitmap(file); const scale=Math.min(1,2400/Math.max(bitmap.width,bitmap.height)); if(scale===1 && file.type==='image/webp') return file; const canvas=document.createElement('canvas'); canvas.width=Math.round(bitmap.width*scale); canvas.height=Math.round(bitmap.height*scale); canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height); const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/webp',.82)); if(!blob) return file; return new File([blob],`${file.name.replace(/\.[^.]+$/,'')}.webp`,{type:'image/webp'}); }
export async function uploadMediaAsset(file:File, altText=''):Promise<MediaAsset>{ const detected=detectedMime(file); if(!allowedTypes.has(detected)) throw new Error('Unsupported file type. SVG is not allowed.'); if(file.size>50*1024*1024) throw new Error('Files must be 50 MB or smaller.'); const prepared=await maybeResize(file); const path=`site/${Date.now()}-${safeName(prepared.name)}`; const {error:uploadError}=await supabase.storage.from(BUCKET).upload(path,prepared,{contentType:detected,upsert:false}); if(uploadError) throw uploadError; const {data:{publicUrl}}=supabase.storage.from(BUCKET).getPublicUrl(path); const mediaType=detected.startsWith('image/')?'image':detected.startsWith('video/')?'video':detected==='application/pdf'?'document':'document'; const row={file_name:prepared.name,asset_url:publicUrl,media_type:mediaType,mime_type:detected,size_bytes:prepared.size,alt_text:altText}; const {data,error}=await supabase.from('media_assets').insert(row).select('*').single(); if(error){await supabase.storage.from(BUCKET).remove([path]);throw error;} return data as MediaAsset; }
export async function deleteMediaAsset(asset:MediaAsset){const marker=asset.asset_url.split(`/storage/v1/object/public/${BUCKET}/`)[1];if(marker) await supabase.storage.from(BUCKET).remove([marker]);const {error}=await supabase.from('media_assets').delete().eq('id',asset.id);if(error)throw error;}
export async function getSettings(): Promise<SiteSettings> { const { data } = await supabase.from('site_settings').select('*').eq('id','global').maybeSingle(); return data ? { ...emptySettings, ...data } : emptySettings; }
export async function getCategories(includeInactive=false): Promise<Category[]> { let q=supabase.from('categories').select('*').order('display_order').order('name');if(!includeInactive)q=q.eq('is_active',true);const {data,error}=await q;if(error)throw error;return data||[]; }
export async function createCategory(input:Pick<Category,'name'|'slug'|'description'|'parent_id'|'display_order'|'is_active'>){const {data,error}=await supabase.from('categories').insert(input).select('*').single();if(error)throw error;return data as Category;}
export async function updateCategory(id:string,input:Partial<Category>){const {data,error}=await supabase.from('categories').update({...input,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data as Category;}
export async function deleteCategory(id:string){const {count}=await supabase.from('projects').select('*',{count:'exact',head:true}).eq('category_id',id);if(count&&count>0)throw new Error(`${count} project(s) use this category. Reassign them before deleting.`);const {error}=await supabase.from('categories').delete().eq('id',id);if(error)throw error;}
export async function getProjects(options: { category?: string; search?: string; featured?: boolean } = {}): Promise<Project[]> { let q = supabase.from('projects').select('*, category:categories(*), media:project_media(*)').eq('status','published').order('display_order').order('published_at',{ascending:false}); if(options.featured) q=q.eq('featured',true); if(options.search) q=q.ilike('title',`%${options.search}%`); const {data,error}=await q;if(error)return [];let projects=(data||[]) as Project[];if(options.category)projects=projects.filter(p=>p.category?.slug===options.category||p.category?.parent_id===options.category);return projects; }
export async function getProject(slug:string):Promise<Project|null>{const {data}=await supabase.from('projects').select('*, category:categories(*), media:project_media(*)').eq('slug',slug).eq('status','published').maybeSingle();return data as Project|null;}
export async function getServices():Promise<Service[]>{const {data}=await supabase.from('company_services').select('*').eq('is_active',true).order('display_order');return data||[];}
export async function getPageSections(page_slug:string):Promise<PageSection[]>{const {data}=await supabase.from('page_sections').select('*').eq('page_slug',page_slug).eq('status','published').eq('is_visible',true).order('display_order');return data||[];}
export async function submitEnquiry(payload:Omit<ContactSubmission,'id'|'status'|'created_at'>&{website?:string}){if(payload.website)return;const {website:_,...row}=payload;const {error}=await supabase.from('contact_submissions').insert(row);if(error)throw error;}
export async function signIn(email:string,password:string):Promise<User>{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.user)throw error||new Error('Unable to sign in');const {data:profile}=await supabase.from('profiles').select('id,email,name,role').eq('id',data.user.id).maybeSingle();if(!profile||!['admin','super_admin'].includes(profile.role)){await supabase.auth.signOut();throw new Error('This account does not have admin access.');}return profile as User;}
export async function currentAdmin():Promise<User|null>{const {data:{user}}=await supabase.auth.getUser();if(!user)return null;const {data}=await supabase.from('profiles').select('id,email,name,role').eq('id',user.id).maybeSingle();return data&&['admin','super_admin'].includes(data.role)?data as User:null;}
export async function signOut(){await supabase.auth.signOut();}
export async function getAdminCounts(){const [{count:projects},{count:drafts},{count:enquiries}]=await Promise.all([supabase.from('projects').select('*',{count:'exact',head:true}).eq('status','published'),supabase.from('projects').select('*',{count:'exact',head:true}).eq('status','draft'),supabase.from('contact_submissions').select('*',{count:'exact',head:true}).eq('status','new')]);return {projects:projects||0,drafts:drafts||0,enquiries:enquiries||0};}
export async function getEnquiries():Promise<ContactSubmission[]>{const {data}=await supabase.from('contact_submissions').select('*').order('created_at',{ascending:false}).limit(50);return data||[];}
export async function updateEnquiry(id:string,status:ContactSubmission['status']){await supabase.from('contact_submissions').update({status}).eq('id',id);}
export async function updateSettings(settings:Partial<SiteSettings>){const {error}=await supabase.from('site_settings').update(settings).eq('id','global');if(error)throw error;}
export async function listAdminProjects():Promise<Project[]>{const {data,error}=await supabase.from('projects').select('*, category:categories(*)').order('updated_at',{ascending:false});if(error)throw error;return data||[];}
export async function saveProject(input:Partial<Project>,id?:string):Promise<Project>{const row={title:input.title,slug:input.slug,summary:input.summary,long_description:input.long_description||null,client:input.client||null,industry:input.industry||null,year:input.year||null,services_provided:input.services_provided||[],tech_stack:input.tech_stack||[],results:input.results||[],live_url:input.live_url||null,repo_url:input.repo_url||null,cover_image:input.cover_image||null,category_id:input.category_id||null,status:input.status||'draft',featured:Boolean(input.featured),display_order:input.display_order||0,seo_title:input.seo_title||null,seo_description:input.seo_description||null,updated_at:new Date().toISOString(),published_at:input.status==='published'?(input.published_at||new Date().toISOString()):null};const query=id?supabase.from('projects').update(row).eq('id',id):supabase.from('projects').insert(row);const {data,error}=await query.select('*, category:categories(*)').single();if(error)throw error;return data as Project;}
export async function removeProject(id:string){const {error}=await supabase.from('projects').delete().eq('id',id);if(error)throw error;}
export async function listMediaAssets():Promise<MediaAsset[]>{const {data,error}=await supabase.from('media_assets').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[];}

export async function listProjectMedia(projectId:string):Promise<import('../types').ProjectMedia[]>{const {data,error}=await supabase.from('project_media').select('*').eq('project_id',projectId).order('display_order');if(error)throw error;return data||[];}
export async function attachProjectMedia(projectId:string,asset:MediaAsset,caption=''){const {count}=await supabase.from('project_media').select('*',{count:'exact',head:true}).eq('project_id',projectId);const row={project_id:projectId,media_asset_id:asset.id,asset_url:asset.asset_url,media_type:asset.media_type,caption:caption||null,display_order:count||0};const {data,error}=await supabase.from('project_media').insert(row).select('*').single();if(error)throw error;return data;}
export async function updateProjectMedia(id:string,input:Partial<{caption:string;display_order:number}>){const {error}=await supabase.from('project_media').update(input).eq('id',id);if(error)throw error;}
export async function removeProjectMedia(mediaId:string){const {error}=await supabase.from('project_media').delete().eq('id',mediaId);if(error)throw error;}
