import { supabase } from './supabase';
import { Category, ContactSubmission, PageSection, Project, Service, SiteSettings, User, emptySettings } from '../types';

export async function getSettings(): Promise<SiteSettings> { const { data } = await supabase.from('site_settings').select('*').eq('id','global').maybeSingle(); return data ? { ...emptySettings, ...data } : emptySettings; }
export async function getCategories(): Promise<Category[]> { const { data, error } = await supabase.from('categories').select('*').eq('is_active',true).order('display_order'); if(error) return []; return data || []; }
export async function getProjects(options: { category?: string; search?: string; featured?: boolean } = {}): Promise<Project[]> { let q = supabase.from('projects').select('*, category:categories(*), media:project_media(*)').eq('status','published').order('display_order').order('published_at',{ascending:false}); if(options.featured) q=q.eq('featured',true); if(options.search) q=q.ilike('title',`%${options.search}%`); const {data,error}=await q; if(error) return []; let projects=(data||[]) as Project[]; if(options.category) projects=projects.filter(p=>p.category?.slug===options.category || p.category?.parent_id===options.category); return projects; }
export async function getProject(slug: string): Promise<Project|null> { const {data}=await supabase.from('projects').select('*, category:categories(*), media:project_media(*)').eq('slug',slug).eq('status','published').maybeSingle(); return data as Project|null; }
export async function getServices(): Promise<Service[]> { const {data}=await supabase.from('company_services').select('*').eq('is_active',true).order('display_order'); return data||[]; }
export async function getPageSections(page_slug: string): Promise<PageSection[]> { const {data}=await supabase.from('page_sections').select('*').eq('page_slug',page_slug).eq('status','published').eq('is_visible',true).order('display_order'); return data||[]; }
export async function submitEnquiry(payload: Omit<ContactSubmission,'id'|'status'|'created_at'> & {website?:string}) { if(payload.website) return; const {website:_,...row}=payload; const {error}=await supabase.from('contact_submissions').insert(row); if(error) throw error; }
export async function signIn(email:string,password:string): Promise<User> { const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error || !data.user) throw error || new Error('Unable to sign in'); const {data:profile}=await supabase.from('profiles').select('id,email,name,role').eq('id',data.user.id).maybeSingle(); if(!profile || !['admin','super_admin'].includes(profile.role)) { await supabase.auth.signOut(); throw new Error('This account does not have admin access.'); } return profile as User; }
export async function currentAdmin(): Promise<User|null> { const {data:{user}}=await supabase.auth.getUser(); if(!user) return null; const {data}=await supabase.from('profiles').select('id,email,name,role').eq('id',user.id).maybeSingle(); return data && ['admin','super_admin'].includes(data.role) ? data as User : null; }
export async function signOut(){ await supabase.auth.signOut(); }
export async function getAdminCounts(){ const [{count:projects},{count:drafts},{count:enquiries}]=await Promise.all([supabase.from('projects').select('*',{count:'exact',head:true}).eq('status','published'),supabase.from('projects').select('*',{count:'exact',head:true}).eq('status','draft'),supabase.from('contact_submissions').select('*',{count:'exact',head:true}).eq('status','new')]); return {projects:projects||0,drafts:drafts||0,enquiries:enquiries||0}; }
export async function getEnquiries(): Promise<ContactSubmission[]> { const {data}=await supabase.from('contact_submissions').select('*').order('created_at',{ascending:false}).limit(50); return data||[]; }
export async function updateEnquiry(id:string,status:ContactSubmission['status']){ await supabase.from('contact_submissions').update({status}).eq('id',id); }
export async function updateSettings(settings:Partial<SiteSettings>){ const {error}=await supabase.from('site_settings').update(settings).eq('id','global'); if(error) throw error; }
export async function listAdminProjects(): Promise<Project[]> { const {data}=await supabase.from('projects').select('*, category:categories(*)').order('updated_at',{ascending:false}); return data||[]; }
