-- Vision Built portfolio CMS v1
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in ('admin','super_admin')); $$;
create table if not exists public.categories(id uuid primary key default gen_random_uuid(), name text not null, slug text not null, description text, parent_id uuid references public.categories(id) on delete set null, display_order int not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists categories_slug_parent_idx on public.categories(slug,coalesce(parent_id,'00000000-0000-0000-0000-000000000000'));
create or replace function public.enforce_two_category_levels() returns trigger language plpgsql as $$ begin if new.parent_id is not null and exists(select 1 from public.categories where id=new.parent_id and parent_id is not null) then raise exception 'Categories support only two levels'; end if; return new; end; $$;
drop trigger if exists categories_two_levels on public.categories; create trigger categories_two_levels before insert or update on public.categories for each row execute function public.enforce_two_category_levels();
create table if not exists public.projects(id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, summary text not null, long_description text, client text, industry text, year int, services_provided text[] not null default '{}', tech_stack text[] not null default '{}', results jsonb not null default '[]', live_url text, repo_url text, cover_image text, category_id uuid references public.categories(id) on delete set null, status text not null default 'draft' check(status in ('draft','published','archived')), featured boolean not null default false, display_order int not null default 0, published_at timestamptz, seo_title text, seo_description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.media_assets(id uuid primary key default gen_random_uuid(), file_name text not null, asset_url text not null, media_type text not null, mime_type text, size_bytes bigint, alt_text text, created_at timestamptz not null default now());
create table if not exists public.project_media(id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, media_asset_id uuid references public.media_assets(id) on delete set null, asset_url text not null, media_type text not null, caption text, display_order int not null default 0);
create table if not exists public.page_sections(id uuid primary key default gen_random_uuid(), page_slug text not null, section_key text not null, content jsonb not null default '{}', display_order int not null default 0, is_visible boolean not null default true, status text not null default 'published' check(status in ('draft','published')), unique(page_slug,section_key));
create table if not exists public.company_services(id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, summary text not null, description text, icon text, display_order int not null default 0, is_active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.team_members(id uuid primary key default gen_random_uuid(), name text not null, role text not null, bio text, image_url text, display_order int not null default 0, is_active boolean not null default true);
create table if not exists public.testimonials(id uuid primary key default gen_random_uuid(), quote text not null, name text not null, company text, image_url text, display_order int not null default 0, is_active boolean not null default true);
create table if not exists public.client_logos(id uuid primary key default gen_random_uuid(), name text not null, image_url text not null, display_order int not null default 0, is_active boolean not null default true);
create table if not exists public.contact_submissions(id uuid primary key default gen_random_uuid(), name text not null, email text not null, phone text, company text, project_type text not null, budget_range text, message text not null, status text not null default 'new' check(status in ('new','read','replied','archived')), internal_notes text, created_at timestamptz not null default now());
alter table public.site_settings add column if not exists company_name text not null default 'Vision Built'; alter table public.site_settings add column if not exists tagline text not null default 'Digital products built with intent.'; alter table public.site_settings add column if not exists logo_light text; alter table public.site_settings add column if not exists logo_dark text; alter table public.site_settings add column if not exists favicon text; alter table public.site_settings add column if not exists whatsapp text; alter table public.site_settings add column if not exists address text; alter table public.site_settings add column if not exists maps_embed text; alter table public.site_settings add column if not exists working_hours text; alter table public.site_settings add column if not exists social_links jsonb not null default '{}'; alter table public.site_settings add column if not exists footer_text text; alter table public.site_settings add column if not exists default_seo_title text not null default 'Vision Built — Digital products built with intent'; alter table public.site_settings add column if not exists default_seo_description text not null default 'Vision Built designs and builds clear, durable digital products for ambitious teams.'; alter table public.site_settings add column if not exists share_image text;
insert into public.site_settings(id) values('global') on conflict do nothing;
alter table public.categories enable row level security; alter table public.projects enable row level security; alter table public.media_assets enable row level security; alter table public.project_media enable row level security; alter table public.page_sections enable row level security; alter table public.company_services enable row level security; alter table public.team_members enable row level security; alter table public.testimonials enable row level security; alter table public.client_logos enable row level security; alter table public.contact_submissions enable row level security;
drop policy if exists public_categories on public.categories; create policy public_categories on public.categories for select using(is_active=true); drop policy if exists admin_categories on public.categories; create policy admin_categories on public.categories for all using(public.is_admin()) with check(public.is_admin());
drop policy if exists public_projects on public.projects; create policy public_projects on public.projects for select using(status='published'); drop policy if exists admin_projects on public.projects; create policy admin_projects on public.projects for all using(public.is_admin()) with check(public.is_admin());
create policy public_media_assets on public.media_assets for select using(true); create policy admin_media_assets on public.media_assets for all using(public.is_admin()) with check(public.is_admin()); create policy public_project_media on public.project_media for select using(exists(select 1 from public.projects p where p.id=project_id and p.status='published')); create policy admin_project_media on public.project_media for all using(public.is_admin()) with check(public.is_admin()); create policy public_page_sections on public.page_sections for select using(status='published' and is_visible=true); create policy admin_page_sections on public.page_sections for all using(public.is_admin()) with check(public.is_admin());
create policy public_company_services on public.company_services for select using(is_active=true); create policy admin_company_services on public.company_services for all using(public.is_admin()) with check(public.is_admin()); create policy public_team_members on public.team_members for select using(is_active=true); create policy admin_team_members on public.team_members for all using(public.is_admin()) with check(public.is_admin()); create policy public_testimonials on public.testimonials for select using(is_active=true); create policy admin_testimonials on public.testimonials for all using(public.is_admin()) with check(public.is_admin()); create policy public_client_logos on public.client_logos for select using(is_active=true); create policy admin_client_logos on public.client_logos for all using(public.is_admin()) with check(public.is_admin());
create policy public_settings on public.site_settings for select using(true); create policy admin_settings on public.site_settings for update using(public.is_admin()) with check(public.is_admin()); create policy public_contact_insert on public.contact_submissions for insert with check(length(name)>0 and length(message)>=20); create policy admin_contact on public.contact_submissions for select using(public.is_admin()); create policy admin_contact_update on public.contact_submissions for update using(public.is_admin()) with check(public.is_admin());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('portfolio-media','portfolio-media',true,52428800,array['image/jpeg','image/png','image/webp','image/avif','image/gif','video/mp4','video/webm','video/quicktime','application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/zip']) on conflict(id) do update set public=true,file_size_limit=52428800;
create policy portfolio_media_read on storage.objects for select using(bucket_id='portfolio-media'); create policy portfolio_media_write on storage.objects for insert with check(bucket_id='portfolio-media' and public.is_admin()); create policy portfolio_media_update on storage.objects for update using(bucket_id='portfolio-media' and public.is_admin()); create policy portfolio_media_delete on storage.objects for delete using(bucket_id='portfolio-media' and public.is_admin());
-- Preserve legacy commerce tables for rollback/audit; the new application does not query them.
alter table if exists public.orders rename to archived_orders; alter table if exists public.payments rename to archived_payments; alter table if exists public.messages rename to archived_messages; alter table if exists public.marketplace_items rename to archived_marketplace_items; alter table if exists public.offers rename to archived_offers; alter table if exists public.tasks rename to archived_tasks; alter table if exists public.project_suggestions rename to archived_project_suggestions; alter table if exists public.recurring_services rename to archived_recurring_services;
